name: shared_preferences
description: Flutter plugin for reading and writing simple key-value pairs.
  Wraps NSUserDefaults on iOS and SharedPreferences on Android.
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences
version: 0.5.6

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.sharedpreferences
        pluginClass: SharedPreferencesPlugin
      ios:
        pluginClass: FLTSharedPreferencesPlugin
      macos:
        default_package: shared_preferences_macos
      web:
        default_package: shared_preferences_web

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter

  shared_preferences_platform_interface: ^1.0.0

  shared_preferences_web:
    git:
      url: https://github.com/luiz-simples/tmp_shared_preferences_web.git

  shared_preferences_macos:
    git:
      url: https://github.com/luiz-simples/tmp_shared_preferences_macos.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.2.0

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.14.1 <2.0.0"
